version: '3.4'

services:
  shome.fulfillment.web:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - MqttConfig__Host=mosquitto
      - MqttConfig__Port=1883
      - MqttConfig__User=""
      - MqttConfig__Password=""
      - MqttConfig__Tls=false
      - GcpDatastoreConfig__ProjectId=shome-assistant
    build:
      context: .
      dockerfile: src/shome.fulfillment.web/docker/Dockerfile
    volumes:
      - ./secrets:/app/secrets


  shome.fulfillment.azure.function:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - MqttConfig__Host=mosquitto
      - MqttConfig__Port=1883
      - MqttConfig__User=""
      - MqttConfig__Password=""
      - MqttConfig__Tls=false
      - GcpDatastoreConfig__ProjectId=shome-assistant
    build:
      context: .
      dockerfile: src/shome.fulfillment.azure.function/docker/Dockerfile
    volumes:
      - ./secrets:/app/secrets
      

  mosquitto:
    image: eclipse-mosquitto:1.5

